language: c

cache: apt

sudo: false
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_script:
  - pushd /tmp
  - mkdir lib-install
  - wget https://github.com/greatscottgadgets/libbtbb/archive/master.zip -O /tmp/libbtbb-master.zip
  - unzip libbtbb-master.zip
  - mkdir libbtbb-master/build
  - cd libbtbb-master/build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/tmp/lib-install ..
  - make
  - make install
  - popd
  - export CFLAGS="-g -Wall -Wextra -Werror -Wno-zero-length-array"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap PX4/homebrew-px4; brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libusb gcc-arm-none-eabi; fi

script:
  - mkdir host/build
  - cd host/build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then DYLIB_SUFFIX=dylib; else DYLIB_SUFFIX=so; fi
  - cmake -DLIBBTBB_INCLUDE_DIR=/tmp/lib-install/include -DLIBBTBB_LIBRARIES=/tmp/lib-install/lib/libbtbb.$DYLIB_SUFFIX -DCMAKE_INSTALL_PREFIX:PATH=/tmp/lib-install ..
  - make
  - make install
  - cd ../../firmware/bluetooth_rxtx
  - export DFU_TOOL="../../host/build/ubertooth-tools/src/ubertooth-dfu"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then install_name_tool -add_rpath /tmp/lib-install/lib/ $DFU_TOOL; fi
  - make

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - libusb-1.0-0-dev
      - libbluetooth-dev
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
